### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ianchan** [NYULibraries/primo-explore-search-bar-sub-menu#7]
Hi,

I keep running into this error. Is it because I am not using browsify?

Thanks for your help.

Ian

**Comment by etgrieco** [comment]
Hi there, sorry for the delay. Yes browserfy is necessary to allow the modules to work. Any luck?

**Comment by etgrieco** [comment]
@ianchan take a peek at our implementation here, https://github.com/NYULibraries/primo-explore-nyu/blob/master/js/main.js

Or share your code so we can better diagnose.

**Comment by ianchan** [comment]
Hi, thank you for the follow-up, and for providing this module! I was able to remove the need for browserfy and the module is working very nicely.
